development:
  adapter: postgresql
  encoding: utf8
  database: recruiterlive_development
  pool: 5
  username: recruiterlive
  password: password

test:
  adapter: postgresql
  encoding: utf8
  database: recruiterlive_test
  pool: 5
  username: recruiterlive
  password: password
